---
abstract: 'Interactive script handling for Bot::Backbone'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Backbone-Service-Interactive
requires:
  AnyEvent::Run: 0
  Bot::Backbone: 0
  Bot::Backbone::Service: 0
  Bot::Backbone::Service::Role::ChatConsumer: 0
  Bot::Backbone::Service::Role::Service: 0
  Scalar::Util: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-Backbone-Service-Interactive
  repository: git://github.com/zostay/Bot-Backbone-Service-Interactive.git
version: 0.142250
